// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSETpP-_GndeDIDN1DNadtf-cQOY3tndA',
    appId: '1:701385362000:web:947d47096482675aa65f55',
    messagingSenderId: '701385362000',
    projectId: 'sms2-9d6eb',
    authDomain: 'sms2-9d6eb.firebaseapp.com',
    storageBucket: 'sms2-9d6eb.appspot.com',
    measurementId: 'G-69VEKY0ZTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDflJ-DCDggHsnkTHH5voTyrIU_-f0j5Q',
    appId: '1:701385362000:android:3928306e3db487fea65f55',
    messagingSenderId: '701385362000',
    projectId: 'sms2-9d6eb',
    storageBucket: 'sms2-9d6eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVb-mFTj1fFKT33alxoL4MdXMyNjTz3e4',
    appId: '1:701385362000:ios:6f71a8c62b707acea65f55',
    messagingSenderId: '701385362000',
    projectId: 'sms2-9d6eb',
    storageBucket: 'sms2-9d6eb.appspot.com',
    iosBundleId: 'com.example.studentManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVb-mFTj1fFKT33alxoL4MdXMyNjTz3e4',
    appId: '1:701385362000:ios:6f71a8c62b707acea65f55',
    messagingSenderId: '701385362000',
    projectId: 'sms2-9d6eb',
    storageBucket: 'sms2-9d6eb.appspot.com',
    iosBundleId: 'com.example.studentManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSETpP-_GndeDIDN1DNadtf-cQOY3tndA',
    appId: '1:701385362000:web:db727bef592dfbe8a65f55',
    messagingSenderId: '701385362000',
    projectId: 'sms2-9d6eb',
    authDomain: 'sms2-9d6eb.firebaseapp.com',
    storageBucket: 'sms2-9d6eb.appspot.com',
    measurementId: 'G-YPDD3S60GN',
  );
}
